// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNPost.DataAccess.Data;

namespace VNPost.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210227151045_AddDB")]
    partial class AddDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "13d23c51-re38-4831-wqa2-2e3f21c23ewd",
                            ConcurrencyStamp = "20e6071b-fbd8-4c55-806a-a79b3b1c4a8b",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "01b96c14-de28-4831-afa9-3d1f84b93aed",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ecff460b-adfc-411e-9f35-5c3bcec94910",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENVfYO/ByyafuleVAgUNZiUlG+Vyi645v0VP2+KuzBuUxIrzqh2Hy0RwzJf21yFrAQ==	",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6ffaeab3-f7bb-4889-8127-35ed8b0f2b53",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "01b96c14-de28-4831-afa9-3d1f84b93aed",
                            RoleId = "13d23c51-re38-4831-wqa2-2e3f21c23ewd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("VNPost.Models.Entity.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int>("ColumnistItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("View")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColumnistItemId");

                    b.HasIndex("DateCreate")
                        .HasName("Index_Article_Date");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("View")
                        .HasName("Index_Article_View");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("VNPost.Models.Entity.CURD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CURDs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Img")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img = "/image/category/ImageCaching.ashx.png",
                            Name = "Bưu chính chuyển phát"
                        },
                        new
                        {
                            Id = 2,
                            Img = "/image/category/ImageCaching.ashx-2.png",
                            Name = "Tài chính bưu chính"
                        },
                        new
                        {
                            Id = 3,
                            Img = "/image/category/ImageCaching.ashx-3.png",
                            Name = "Phân phối - Truyền thông"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.Columnist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Columnists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tin Vietnam Post"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bưu điện - Văn hóa xã"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Người bưu điện"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hoạt động Đảng - Đoàn thể"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.ColumnistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColumnistId");

                    b.ToTable("ColumnistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColumnistId = 1,
                            Name = "Hoạt động ngành"
                        },
                        new
                        {
                            Id = 2,
                            ColumnistId = 1,
                            Name = "Thương mại điện tử"
                        },
                        new
                        {
                            Id = 3,
                            ColumnistId = 1,
                            Name = "Hành chính công"
                        },
                        new
                        {
                            Id = 4,
                            ColumnistId = 1,
                            Name = "Lương hưu - bảo trợ xã hội"
                        },
                        new
                        {
                            Id = 5,
                            ColumnistId = 1,
                            Name = "Điểm chi trả chế độ BHXH"
                        },
                        new
                        {
                            Id = 6,
                            ColumnistId = 1,
                            Name = "Bưu chính thế giới"
                        },
                        new
                        {
                            Id = 7,
                            ColumnistId = 3,
                            Name = "Gương điển hình"
                        },
                        new
                        {
                            Id = 8,
                            ColumnistId = 3,
                            Name = "Hoạt động cộng đồng"
                        },
                        new
                        {
                            Id = 9,
                            ColumnistId = 3,
                            Name = "Viết thư UPU"
                        },
                        new
                        {
                            Id = 10,
                            ColumnistId = 3,
                            Name = "Cuộc thi ảnh bưu điện trong tôi"
                        },
                        new
                        {
                            Id = 11,
                            ColumnistId = 3,
                            Name = "Tìm hiểu Tem Bưu chính"
                        },
                        new
                        {
                            Id = 12,
                            ColumnistId = 4,
                            Name = "Công tác Đảng"
                        },
                        new
                        {
                            Id = 13,
                            ColumnistId = 4,
                            Name = "Công đoàn"
                        },
                        new
                        {
                            Id = 14,
                            ColumnistId = 4,
                            Name = "Đoàn thanh niên"
                        },
                        new
                        {
                            Id = 15,
                            ColumnistId = 4,
                            Name = "Góp ý xây dựng cơ chế - chính sách"
                        },
                        new
                        {
                            Id = 16,
                            ColumnistId = 2,
                            Name = "Bưu điện - Văn hóa xã"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("VNPost.Models.Entity.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Galleries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bưu điện Việt Nam vì một cuộc sống xanh",
                            ImgDescription = "/image/gallery/Recycle.png",
                            Title = "Nói không với rác thải nhựa"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tổng hợp báo chí ngành bưu điện",
                            ImgDescription = "/image/gallery/newspaper.png",
                            Title = "Tổng hợp báo chí"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Văn bản quản lý chất lượng dịch vụ",
                            ImgDescription = "/image/gallery/quan-ly-chat-luong.png",
                            Title = "Quản lý chất lượng"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Văn bản quản lý tem bưu chính",
                            ImgDescription = "/image/gallery/stamp.png",
                            Title = "Tem bưu chính"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tổng hợp thông tin thi đua khen thưởng",
                            ImgDescription = "/image/gallery/thi-dua-khen-thuong.png",
                            Title = "Thi đua - khen thưởng"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Văn bản pháp lý và các thông tin liên quan",
                            ImgDescription = "/image/gallery/folder.png",
                            Title = "Văn bản pháp lý"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Hướng tới Đại hội Đại biểu Đảng bộ TCT lần II",
                            ImgDescription = "/image/gallery/Icon-Dang.png",
                            Title = "Đại hội Đảng"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Chuyên trang thông tin doanh nghiệp",
                            ImgDescription = "/image/gallery/list-top.png",
                            Title = "Thông tin Doanh nghiệp"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DistricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParcelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DistricId");

                    b.HasIndex("ParcelId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("VNPost.Models.Entity.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            Key = "Company",
                            Value = "TỔNG CÔNG TY BƯU ĐIỆN VIỆT NAM - VIETNAM POST"
                        },
                        new
                        {
                            Id = 10,
                            Key = "Location",
                            Value = "Địa chỉ: Số 05 đường Phạm Hùng - Mỹ Đình 2 - Nam Từ Liêm - Hà Nội - Việt Nam"
                        },
                        new
                        {
                            Id = 11,
                            Key = "Policy",
                            Value = "Ghi rõ nguồn \"www.vnpost.vn\" khi phát hành lại thông tin từ website này"
                        },
                        new
                        {
                            Id = 12,
                            Key = "Ra mắt nền tảng mã địa chỉ bưu chính - Vpostcode",
                            Value = "https://www.youtube.com/embed/iPEvFyikq-g"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.MenuLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("MenuLinks");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Key = "",
                            Link = "/Posts/Service/List/1",
                            LocationId = 4,
                            Value = "Bưu chính chuyển phát"
                        },
                        new
                        {
                            Id = 9,
                            Key = "",
                            Link = "/Posts/Service/List/2",
                            LocationId = 4,
                            Value = "Tài chính bưu chính"
                        },
                        new
                        {
                            Id = 10,
                            Key = "",
                            Link = "/Posts/Service/List/3",
                            LocationId = 4,
                            Value = "Phân phối -Truyền thông"
                        },
                        new
                        {
                            Id = 11,
                            Key = "",
                            Link = "/Posts/Article/List",
                            LocationId = 4,
                            Value = "Tin tức"
                        },
                        new
                        {
                            Id = 31,
                            Key = "",
                            Link = "https://www.facebook.com/vnpost.vn",
                            LocationId = 8,
                            Value = "fab fa-facebook-f"
                        },
                        new
                        {
                            Id = 32,
                            Key = "",
                            Link = "https://twitter.com/buudienvietnam",
                            LocationId = 8,
                            Value = "fab fa-twitter"
                        },
                        new
                        {
                            Id = 33,
                            Key = "",
                            Link = "https://www.linkedin.com/authwall?trk=gf&trkInfo=AQEcHBePbUPbnwAAAXKW4SzYfqas88PMwWIydrQUKt7vRdlRm_Thesf7HIcEsfHSkUXiZuX_nMjyj4IfViiABffUTA0XRALzYNn5xU6ph_mz0P_XK4651j2JANKqojtkFw3fRAk=&originalReferer=http://www.vnpost.vn/&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ftt-dvkh-529b25197%2F",
                            LocationId = 8,
                            Value = "fab fa-linkedin"
                        },
                        new
                        {
                            Id = 34,
                            Key = "",
                            Link = "http://www.vnpost.vn/desktopmodules/vnp_webapi/rssfeed.aspx",
                            LocationId = 8,
                            Value = "fab fa-instagram"
                        },
                        new
                        {
                            Id = 35,
                            Key = "",
                            Link = "#",
                            LocationId = 9,
                            Value = "/image/slider/banner1.jpg"
                        },
                        new
                        {
                            Id = 36,
                            Key = "",
                            Link = "#",
                            LocationId = 9,
                            Value = "/image/slider/banner2.jpg"
                        },
                        new
                        {
                            Id = 37,
                            Key = "",
                            Link = "#",
                            LocationId = 9,
                            Value = "/image/slider/banner3.jpg"
                        },
                        new
                        {
                            Id = 38,
                            Key = "",
                            Link = "#",
                            LocationId = 9,
                            Value = "/image/slider/banner4.jpg"
                        },
                        new
                        {
                            Id = 39,
                            Key = "SÀN THƯƠNG MẠI ĐIỆN TỬ POSTMART",
                            Link = "#",
                            LocationId = 10,
                            Value = "/image/other/ImageCaching.ashx.jpeg"
                        },
                        new
                        {
                            Id = 40,
                            Key = "LỊCH TẾT",
                            Link = "#",
                            LocationId = 10,
                            Value = "/image/other/ImageCaching.ashx.png"
                        },
                        new
                        {
                            Id = 41,
                            Key = "DỊCH VỤ DATAPOST",
                            Link = "#",
                            LocationId = 10,
                            Value = "/image/other/ImageCaching.ashx-2.jpeg"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.MenuLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrtiption")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuLocations");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Name = "Bottom-menu"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mạng xã hội"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Slider"
                        },
                        new
                        {
                            Id = 10,
                            Descrtiption = "Hiện tại chúng tôi có những gian hàng mua sắm online với đầy đủ những sản phẩm tiện ích, đa dạng. Hy vọng sẽ đem đến cho quý khách hàng những trải nghiệm mua sắm mới mẻ nhất. Hãy đến với hệ thống mua sắm trực tuyến của chúng tôi để tìm cho mình những sản phẩm thiết thực nhất.",
                            Name = "Mua sắm trực tuyến"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PointAway")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("VNPost.Models.Entity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionImg")
                        .HasColumnType("TEXT");

                    b.Property<int>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Là dịch vụ chuyển phát nhanh thư, tài liệu, vật phẩm, hàng hóa từ người gửi đến người nhận giữa Việt Nam trong nước và các nước trên thế giới trong khuôn khổ Liên minh Bưu chính Thế giới (UPU) và Hiệp hội EMS theo chỉ tiêu thời gian được Công ty Cổ phần Chuyển Phát Nhanh Bưu điện công bố trước. Chi tiết xin tham khảo tại website: www.ems.com.vn",
                            DescriptionImg = "/image/post/ImageCaching.ashx.jpeg",
                            GalleryId = 1,
                            Title = "Chuyển phát nhanh EMS"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bưu phẩm bảo đảm là dịch vụ chấp nhận, vận chuyển và phát bưu phẩm đến địa chỉ nhận trong nước và quốc tế; bưu phẩm được gắn số hiệu để theo dõi, định vị trong quá trình chuyển phát.",
                            DescriptionImg = "/image/post/ImageCaching.ashx-2.jpeg",
                            GalleryId = 1,
                            Title = "Bưu phẩm đảm bảo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Là dịch vụ giới thiệu, chào bán bảo hiểm, thu xếp việc giao kết hợp đồng bảo hiểm thông qua mạng lưới bưu cục, điểm cung cấp dịch vụ của Tổng Công ty Bưu điện Việt Nam.",
                            DescriptionImg = "/image/post/ImageCaching-3.ashx.jpeg",
                            GalleryId = 2,
                            Title = "Bảo hiểm phi nhân thọ PTI"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Là dịch vụ cho phép khách hàng nộp tiền phí bảo hiểm, vay trả góp, tiền điện, nước, cước điện thoại, tiền đặt chỗ, mua hàng qua mạng, tiền phí phạt vi phạm giao thông, tiền thuế, tiền lệ phí hồ sơ xét tuyển ĐH,CĐ, tiền cấp đổi CMND, Hộ chiếu, tiền đặt vé máy bay…tại bưu cục",
                            DescriptionImg = "/image/post/ImageCaching-4.ashx.jpeg",
                            GalleryId = 2,
                            Title = "Thu hộ - Chi hộ"
                        },
                        new
                        {
                            Id = 5,
                            Description = "POSTMART là sàn giao dịch thương mại điện tử được sáng lập bởi Tổng Công ty Bưu Điện Việt Nam (VNPost) và vận hành bởi Công ty Phát hành báo chí TW.",
                            DescriptionImg = "/image/post/ImageCaching-5.ashx.jpeg",
                            GalleryId = 3,
                            Title = "Sàn thương mại điện tử POSTMART"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Truyền thông quảng cáo qua các xuất bản phẩm, hệ thống truyền thông quảng cáo ngoài trời, tại các bưu cục, trên các phương tiện vận tải, phong bì...",
                            DescriptionImg = "/image/post/ImageCaching-6.ashx.jpeg",
                            GalleryId = 3,
                            Title = "Truyền thông, quảng cáo"
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("VNPost.Models.Entity.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnistItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Create")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Delete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Update")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColumnistItemId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("VNPost.Models.Entity.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "<p>Toàn quốc và trên 100 quốc gia và vùng lãnh thổ khắp thế giới theo thoả thuận giữa Công ty và Bưu chính các nước thuộc Liên minh Bưu chính Thế giới (UPU) hoặc các đối tác khác.</p>",
                            Name = "Phạm vi cung cấp",
                            PostId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "<h4>Khối lượng:</h4><br/><p>- Khối lượng bưu gửi EMS thông thường: Tối đa 31,5kg/bưu gửi.</p><br /><p>- Đối với bưu gửi là hàng nguyên khối không thể tách rời, vận chuyển bằng đường bộ được nhận gửi tối đa đến 50kg, nhưng phải đảm bảo giới hạn về kích thước theo quy định.</p><br /><p>- Đối với bưu gửi là hàng nhẹ (hàng có khối lượng thực tế nhỏ hơn khối lượng qui đổi), khối lượng tính cước không căn cứ vào khối lượng thực tế mà căn cứ vào khối lượng qui đổi theo cách tính như sau: Khối lượng qui đổi (kg) = Chiều dài x Chiều rộng x Chiều cao (cm) / 6000</p><br /><p>- Đối với bưu gửi quốc tế: Thực hiện theo thông báo của Công ty Cổ phần Chuyển phát nhanh Bưu điện đối với từng nước.</p><br /><h4>Kích thước:</h4><br /><p>- Kích thước tối thiểu:</p><br /><p>+ Ít nhất một mặt bưu gửi có kích thước không nhỏ hơn 90mm x 140mm với sai số 2 mm.</p><br /><p>+ Nếu cuộn tròn: Chiều dài bưu gửi cộng hai lần đường kính tối thiểu 170 mm và kích thước chiều lớn nhất không nhỏ  hơn 100mm.</p><br /><p>- Kích thước tối đa: Bất kỳ chiều nào của bưu gửi không vượt quá 1500mm và tổng chiều dài cộng với chu vi lớn nhất (không đo theo chiều dài đã đo) không vượt quá 3000mm.</p><br /><p>- Bưu gửi có kích thước lớn hơn so với kích thước thông thường được gọi là bưu gửi cồng kềnh và có quy định riêng phụ thuộc vào từng nơi nhận, nơi phát và điều kiện phương tiện vận chuyển.</p><br /><p>- Đối với bưu gửi quốc tế: Kích thước thông thường đối với bưu gửi EMS là bất kỳ chiều nào của bưu gửi cũng không vượt quá 1,5m và tổng chiều dài cộng với chu vi lớn nhất (không đo theo chiều dài đã đo) không vượt quá 3m.</p><br />",
                            Name = "Khối lượng, kích thước",
                            PostId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "<p>Tùy theo từng dịch vụ sẽ có bảng cước giá khác nhau kèm theo phí dịch vụ của các dịch vụ cộng thêm.</p><p>Bảng cước dịch vụ chuyển phát nhanh EMS trong nước</p><p>Bảng cước dịch vụ chuyển phát nhanh EMS quốc tế</p>",
                            Name = "Cước phí",
                            PostId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "<p>Toàn quốc</p>",
                            Name = "Phạm vi cung cấp dịch vụ",
                            PostId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "<h4>a. Giới hạn kích thước của bưu thiếp:</h4><br/><p>- Kích thước tối đa: 165 mm x 245 mm, với sai số 2 mm.</p><br /><p>- Kích thước tối thiểu: 90 mm x 140 mm, với sai số 2 mm. </p><br /><p>- Tỷ lệ tối thiểu giữa chiều dài và chiều rộng: dài = rộng x  (≈ 1,4).</p><br /><h4>b. Giới hạn kích thước của gói nhỏ: </h4><br /><p>- Kích thước tối thiểu: 210 x 148 mm.</p><br /><p>- Kích thước tối đa: Tổng chiều dài, chiều rộng và chiều cao là 900 mm, nhưng kích thước chiều lớn nhất không vượt quá 600 mm, với sai số 2 mm. Nếu cuộn tròn, chiều dài cộng hai lần đường kính là 1040 mm, nhưng kích thước lớn nhất không vượt quá 900 mm.</p><br /><h4>c. Giới hạn kích thước của các loại bưu phẩm khác:</h4><br /><p>- Kích thước tối đa: Tổng chiều dài, chiều rộng và chiều cao là 900 mm, nhưng kích thước chiều lớn nhất không vượt quá 600 mm, với sai số 2 mm. Nếu cuộn tròn, chiều dài cộng hai lần đường kính là 1040 mm, nhưng kích thước lớn nhất không vượt quá 900 mm, với sai số 2 mm.</p><br /><p>- Kích thước tối thiểu: Một mặt kích thước không nhỏ hơn 90 mm x 140 mm với sai số 2 mm. Nếu cuộn tròn: chiều dài cộng hai lần đường kính là 170 mm, nhưng kích thước chiều lớn nhất không nhỏ hơn 100 mm</p><br />",
                            Name = "Quy định về khối lượng / kích thước",
                            PostId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "<p>Tất cả các điểm cung cấp dịch vụ của Bưu điện Việt Nam trên toàn quốc</p>",
                            Name = "Phạm vi cung cấp dịch vụ",
                            PostId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "<p>Mức phí bảo hiểm cạnh tranh với nhiều chương trình bán hàng hấp dẫn.</p><br/><p>Liên hệ với các điểm bán hàng của Bưu điện trên toàn quốc để biết thông tin phí bảo hiểm chi tiết.</p>",
                            Name = "Bảng cước dịch vụ",
                            PostId = 3
                        },
                        new
                        {
                            Id = 8,
                            Content = "<p>Tất cả các điểm cung cấp dịch vụ của Bưu điện Việt Nam trên toàn quốc</p>",
                            Name = "Phạm vi cung cấp dịch vụ",
                            PostId = 4
                        },
                        new
                        {
                            Id = 9,
                            Content = "<p>Giá cước được thỏa thuận tùy theo từng đối tác và theo sản lượng giao dịch.</p>",
                            Name = "Bảng cước dịch vụ",
                            PostId = 4
                        },
                        new
                        {
                            Id = 10,
                            Content = "<p>Trên toàn Quốc!</p>",
                            Name = "Phạm vi cung cấp dịch vụ",
                            PostId = 5
                        },
                        new
                        {
                            Id = 11,
                            Content = "<p>Dịch vụ thương mại điện tử hay con gọi là E-commerce là hoạt động kinh doanh, mua bán các loại sản phẩm hàng hóa/ dịch vụ diễn ra trên môi trường internet, đặc biệt là thông qua các website và ứng dụng di động. Các hoạt động diễn ra chủ yếu theo 3 hình thức B2C, B2B và C2C</p>",
                            Name = "Đặc điểm dịch vụ",
                            PostId = 5
                        },
                        new
                        {
                            Id = 12,
                            Content = "<p>Tất cả các điểm giao dịch trên 63 tỉnh, thành phố</p>",
                            Name = "Phạm vi cung cấp dịch vụ",
                            PostId = 6
                        },
                        new
                        {
                            Id = 13,
                            Content = "<i>Theo thỏa thuận trên cơ sở đơn giá thị trường</i>",
                            Name = "Bảng cước dịch vụ",
                            PostId = 6
                        });
                });

            modelBuilder.Entity("VNPost.Models.Entity.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Prepare"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VNPost.Models.Entity.Article", b =>
                {
                    b.HasOne("VNPost.Models.Entity.ColumnistItem", "ColumnistItem")
                        .WithMany()
                        .HasForeignKey("ColumnistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");
                });

            modelBuilder.Entity("VNPost.Models.Entity.ColumnistItem", b =>
                {
                    b.HasOne("VNPost.Models.Entity.Columnist", "Columnist")
                        .WithMany()
                        .HasForeignKey("ColumnistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VNPost.Models.Entity.District", b =>
                {
                    b.HasOne("VNPost.Models.Entity.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VNPost.Models.Entity.Location", b =>
                {
                    b.HasOne("VNPost.Models.Entity.District", "District")
                        .WithMany()
                        .HasForeignKey("DistricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VNPost.Models.Entity.Parcel", "Parcel")
                        .WithMany()
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VNPost.Models.Entity.MenuLink", b =>
                {
                    b.HasOne("VNPost.Models.Entity.MenuLocation", "MenuLocation")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VNPost.Models.Entity.Parcel", b =>
                {
                    b.HasOne("VNPost.Models.Entity.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VNPost.Models.Entity.Post", b =>
                {
                    b.HasOne("VNPost.Models.Entity.Gallery", "Gallery")
                        .WithMany()
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VNPost.Models.Entity.RolePermission", b =>
                {
                    b.HasOne("VNPost.Models.Entity.ColumnistItem", "ColumnistItem")
                        .WithMany()
                        .HasForeignKey("ColumnistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("VNPost.Models.Entity.Service", b =>
                {
                    b.HasOne("VNPost.Models.Entity.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
